/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Entidades.Paciente;
import ModeloRecepcionista.CargarCombo;
import ModeloRecepcionista.Conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author RojeruSan
 */
public class VistaFichas extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    Connection con;
    DefaultTableModel model;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    private TableRowSorter trsfiltro;

    public VistaFichas() {
        initComponents();
        CargarPaciente();
    }

    public void CargarPaciente() {
        CargarCombo cargarCombo = new CargarCombo();
        ArrayList<Paciente> listaPaciente = cargarCombo.getPaciente();

        for (int i = 0; i < listaPaciente.size(); i++) {
            comboPaciente.addItem(listaPaciente.get(i).getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpaciente = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        comboPaciente = new javax.swing.JComboBox<>();

        title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title.setText("Fichas Paciente");

        tblpaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habitos", "Alergias", "Cirugias", "Hospitalizaciones", "Antecedentes Morbidos", "Peso", "Talla", "IMC", "Frecuencia Cardiaca", "Frecuencia Respiratoria", "so2", "Presión Arterial", "Descripción Dolor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpaciente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblpaciente.setColumnSelectionAllowed(true);
        tblpaciente.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblpaciente.setShowGrid(false);
        tblpaciente.getTableHeader().setReorderingAllowed(false);
        tblpaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpacienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpaciente);
        tblpaciente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Buscar por rut:");

        comboPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Seleccionado" }));
        comboPaciente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPacienteItemStateChanged(evt);
            }
        });
        comboPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(comboPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(605, 605, 605)
                        .addComponent(title)))
                .addContainerGap(558, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void tblpacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpacienteMouseClicked


    }//GEN-LAST:event_tblpacienteMouseClicked

    private void comboPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPacienteActionPerformed
        listar();
        
    }//GEN-LAST:event_comboPacienteActionPerformed

    private void comboPacienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPacienteItemStateChanged
        // TODO add your handling code here
    }//GEN-LAST:event_comboPacienteItemStateChanged

    public void listar() {
        String id = comboPaciente.getSelectedItem().toString();
        String sql = "SELECT habitos,alergias,cirugias,hospitalizaciones,antecedentes_morbidos,peso,talla,imc,frecuencia_cardiaca,frecuencia_respiratoria,so2,presion_arterial,descripcion_dolor,paciente_id "
                + "FROM `expediente` where paciente_id = '" + id + "';";
        try {
            con = Conexion.getConexion();
            st = con.prepareStatement(sql);
            rs = st.executeQuery(sql);
            Object[] paciente = new Object[13];
//            String[] Titulos={"ID","DNI","NOMBRES"};         
//            model=new DefaultTableModel(null,Titulos);   
            model = (DefaultTableModel) tblpaciente.getModel();
            while (rs.next() == true) {
                // paciente[0] = rs.getInt("id");
                paciente[0] = rs.getString("habitos");
                paciente[1] = rs.getString("alergias");
                paciente[2] = rs.getString("cirugias");
                paciente[3] = rs.getString("hospitalizaciones");
                paciente[4] = rs.getString("antecedentes_morbidos");
                paciente[5] = rs.getString("peso");
                paciente[6] = rs.getString("talla");
                paciente[7] = rs.getString("imc");
                paciente[8] = rs.getString("frecuencia_cardiaca");
                paciente[9] = rs.getString("frecuencia_respiratoria");
                paciente[10] = rs.getString("so2");
                paciente[11] = rs.getString("presion_arterial");
                paciente[12] = rs.getString("descripcion_dolor");

                model.addRow(paciente);
            }
            tblpaciente.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Listar: " + e);
            System.out.println(e);
        }

    }

    public void limpiar() {
        DefaultTableModel tb = (DefaultTableModel) tblpaciente.getModel();
        int a = tblpaciente.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> comboPaciente;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblpaciente;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
